DROP TABLE IF EXISTS refresh_tokens CASCADE;
DROP TABLE IF EXISTS gcal_sync_state CASCADE;
DROP TABLE IF EXISTS tax_year_configs CASCADE;
DROP TABLE IF EXISTS invoices CASCADE;
DROP TABLE IF EXISTS shift_earnings CASCADE;
DROP TABLE IF EXISTS shifts CASCADE;
DROP TABLE IF EXISTS recurrence_rules CASCADE;
DROP TABLE IF EXISTS pricing_rules CASCADE;
DROP TABLE IF EXISTS workplaces CASCADE;
DROP TABLE IF EXISTS users CASCADE;

DROP TYPE IF EXISTS earning_status;
DROP TYPE IF EXISTS day_of_week;
DROP TYPE IF EXISTS shift_status;
DROP TYPE IF EXISTS pay_model;

DROP EXTENSION IF EXISTS "btree_gist";
DROP EXTENSION IF EXISTS "uuid-ossp";
